### ISSUE TITLE
mzMLb

### ISSUE THREAD

**Issue by mobiusklein** [soerendip/ms-mint#23]
Hello,

I've seen you cross-post a few places regarding mzMLb reading and writing. The current development version of https://github.com/levitsky/pyteomics has support for mzMLb reading, and the last release of `psims` includes an mzML to mzMLb conversion tool:

```python
from psims.transform.mzml import MzMLToMzMLb

MzMLToMzMLb("mzml_path", "mzmlb_path").write()
```

Both require `h5py` and `hdf5plugin`.

**Comment by soerendip** [comment]
Amazing. I will give it a try. Thank you!!

________________________________
From: Joshua Klein ***@***.***>
Sent: Wednesday, April 28, 2021 10:14:04 AM
To: soerendip/ms-mint ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [soerendip/ms-mint] mzMLb (#23)


Hello,

I've seen you cross-post a few places regarding mzMLb reading and writing. The current development version of https://github.com/levitsky/pyteomics has support for mzMLb reading, and the last release of psims includes an mzML to mzMLb conversion tool:

from psims.transform.mzml import MzMLToMzMLb

MzMLToMzMLb("mzml_path", "mzmlb_path").write()

Both require h5py and hdf5plugin.

**Comment by mobiusklein** [comment]
This was all written pretty quickly, so if you encounter issues please let me know. Also, because mzMLb is an HDF5 file, it was written with extensibility in mind.

If there are particular search or metadata indices you think would be useful to have, that would be good to know about. I know a lot of people write index files that sit beside their spectra files to store extra metadata, but mzMLb has the capacity to include them directly without violating compatibility.
